# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='farm_shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sequence_number', models.IntegerField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='households',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('monthly_income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.households')),
            ],
        ),
        migrations.CreateModel(
            name='season_wise_crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.crops')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='well_observations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('water_yield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='wells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('avg_water_yield', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='well_observations',
            name='well_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.wells'),
        ),
        migrations.AddField(
            model_name='farm',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.households'),
        ),
    ]
