# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season_wise_crop',
            name='area_cultivated',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
