# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0002_season_wise_crop_area_cultivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='wells',
            name='farm_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Farms.farm'),
            preserve_default=False,
        ),
    ]
