# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0003_wells_farm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wells',
            name='depth',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
