# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0004_wells_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='house_image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
