# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0005_households_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='image_link',
            field=models.CharField(default='https://image.ibb.co/gGzxBG/11.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
