# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 06:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0006_households_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_points',
            field=django.contrib.gis.db.models.fields.PolygonField(default='POLYGON(( 10 10, 10 20, 20 20, 20 15, 10 10))', srid=4326),
        ),
    ]
