# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0008_auto_20171006_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='person_count',
            field=models.IntegerField(default=1),
        ),
    ]
