# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0009_households_person_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_link',
            field=models.CharField(default='https://image.ibb.co/c13FGG/farm.jpg', max_length=1000),
        ),
    ]
